### ISSUE TITLE
Замечания по программе replace

### ISSUE THREAD

**Issue by alexey-malov** [daria-grebneva/OOP#4]
```
1>c:\teaching\2018\oop\grebneva\oop\lr_01\replace\replace.cpp(17): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>c:\teaching\2018\oop\grebneva\oop\lr_01\replace\replace.cpp(53): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
```
- [x] Программа должна компилироваться без предупреждений компилятора во всех конфигурациях и платформах.

**Comment by alexey-malov** [comment]
https://github.com/daria-grebneva/OOP/blob/c2e4bd88849360b64ce863ced221abb2948a72d9/LR_01/replace/replace.cpp#L9-L64

- [ ] Сделайте проще, используя методы, предоставляемые классом string

**Comment by alexey-malov** [comment]
https://github.com/daria-grebneva/OOP/blob/c2e4bd88849360b64ce863ced221abb2948a72d9/LR_01/replace/replace.cpp#L37-L44

- [ ] Зачем здесь цикл, ведь условие выполнится только один раз и в известный момент

**Comment by alexey-malov** [comment]
https://github.com/daria-grebneva/OOP/blob/c2e4bd88849360b64ce863ced221abb2948a72d9/LR_01/replace/replace.cpp#L31-L34

- [ ] Есть метод append

**Comment by alexey-malov** [comment]
https://github.com/daria-grebneva/OOP/blob/b3cededc5f105e10674401bb94f2c6eee932997f/LR_01/replace/replace.cpp#L9-L32

- [ ] Устранить дублирующиеся вызовы append и find

**Comment by alexey-malov** [comment]
- [ ] Выделить из main функцию, выполняющую копирование файла с заменой текста, которая бы принимала имена входного и выходного файлов и выполняла их открытие

**Comment by alexey-malov** [comment]
```
1>c:\teaching\2018\oop\grebneva\oop\lr_01\replace\replace.cpp(17): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
1>c:\teaching\2018\oop\grebneva\oop\lr_01\replace\replace.cpp(19): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
1>c:\teaching\2018\oop\grebneva\oop\lr_01\replace\replace.cpp(25): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
```
- [ ] Программа должна компилироваться без предупреждений компилятора во всех конфигурациях и платформах.

**Comment by alexey-malov** [comment]
- [ ] Программа зависла при запуске тестов в 64 битной отладочной конфигурации

**Comment by oMystique** [comment]
-[ ] Подобрать другое имя для функции `ChangeString`

**Comment by oMystique** [comment]
- [ ] Вынести в отдельный файл функционал, связанный с заменой подстроки в строке
