### ISSUE TITLE
Замечания по программе Invert

### ISSUE THREAD

**Issue by alexey-malov** [daria-grebneva/OOP#7]
```c++
double GetMinor2x2Matrix(Matrix3x3& matrix, int col, int row)
```

- [x] Передавать по константной ссылке матрицу, т.к. функция не меняет ее значение
- [x] Функция большая. Подумайте, как сделать ее меньше, либо проще

**Comment by alexey-malov** [comment]
```c++
double GetСofactor2x2Matrix(double& minor, int minorF, int minorS)
{
	//домножать на -1 в зависимости от нечетности minorF + minorS
	double сofactor = pow(-1, minorF + minorS) * minor;
	return сofactor;
}
```

- [ ] нет смысла передавать double по ссылке. можно передать по значению
- [ ] minorF и minorS - плохие имена
- [ ] GetСofactor2x2Matrix - ПолучитьМатрицуАлгебраических дополнений. 2*2 тут никак не фигурирует.
- [ ] Вообще лучше выпилить и менять знак переменной с -1 на +1 и обратно вычитая ее из нуля

**Comment by alexey-malov** [comment]
- [ ] Выделить из main функцию инвертирования матрицы

**Comment by alexey-malov** [comment]
```c++
double FindCofactor(double minor, int minorOne, int minorTwo)
{
	double сofactor;
	((minorOne + minorTwo) % 2 == 0) ? сofactor = minor : сofactor = -minor;

	return сofactor;
}
```

- [ ] не используйте тернарное выражение таким образом. Упростите его, перенеся присваивание в левую часть иснтрукции:
```c++
return (условие) ? minor : -minor
```

**Comment by alexey-malov** [comment]
- [ ] Выделить из main функцию открытия файла, заданного именем

**Comment by alexey-malov** [comment]
```
3>c:\teaching\2018\oop\grebneva\oop\lr_01\invert\invert.cpp(85): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
3>c:\teaching\2018\oop\grebneva\oop\lr_01\invert\invert.cpp(86): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
```
- [ ] Программа должна компилироваться без предупреждений компилятора во всех конфигурациях и платформах.

**Comment by alexey-malov** [comment]
```c++
	const string nameInputFile = argv[1];
	Matrix3x3 matrix;
	if (ReadMatrix(matrix, nameInputFile))
```

- [ ] nameInputFile -> inputFileName

**Comment by alexey-malov** [comment]
```c++
void GetСofactorOfMatrix(const Matrix3x3& matrix, Matrix3x3& algebraicComplementsMatrix)
{
	for (size_t row = 0; row < SIZE_OF_MATRIX; ++row)
	{
		for (size_t col = 0; col < SIZE_OF_MATRIX; ++col)
		{
			double minor = GetMinorOfMatrix(matrix, row, col);
			algebraicComplementsMatrix[row][col] = FindCofactor(minor, row + 1, col + 1);
		}
	}
}
```
- [ ] Использовать единую терминологию в имени функции и её выходных аргументах

**Comment by alexey-malov** [comment]
MatrixTranspose -> TransposeMatrix

**Comment by oMystique** [comment]
- [ ] Добавить тест, в котором детерминант = 0

**Comment by oMystique** [comment]
- [ ] В функции GetNextLine следует использовать тернарный оператор

**Comment by oMystique** [comment]
- [ ] Нужны нормальные названия для аргументов функции FindCofactor

**Comment by oMystique** [comment]
- [ ] Функционал по работе по работе с матрицами нужно вынести в отдельную пару файлов .cpp/.h
